## This is an example of a simple Neural Network 

In [71]:
import numpy as np

In [72]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [73]:
def sigmoid_prime(x):
    return sigmoid(x)*(1-sigmoid(x))

In [74]:
training_inputs = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

In [75]:
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [76]:
training_outputs = np.array([[0,1,1,0]]).T

In [77]:
training_outputs.shape

(4, 1)

In [78]:
np.random.seed(1)

In [79]:
synaptic_weights = 2*np.random.random((3,1))-1

In [80]:
print ('Random starting synaptic weights: ')
print (synaptic_weights)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [81]:
for iteration in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_prime(outputs)
    
    synaptic_weights = synaptic_weights + np.dot(input_layer.T, adjustments)

In [82]:
print ('Synaptic weights after training')
print (synaptic_weights)

Synaptic weights after training
[[16.42682746]
 [-0.40573462]
 [-7.92781468]]


In [83]:
print ('Outputs after training: ')
print (np.round(outputs,2))

Outputs after training: 
[[0.]
 [1.]
 [1.]
 [0.]]
